

INCLUDES =  -I .\\  -I..\inc\\  -I..\qlinc\\

OBJS= customer.o \
	customerconfig\ql_customer_gpio.o \
	customerconfig\ql_customer_config.o \
	user1\user1.o \
	user2\user2.o \
	user1\subusr1\subusr1.o


SUBPATHS= customerconfig \
	user1 \
	user2 \
	user1\subusr1


all:mksubpaths  listobj $(OBJS)

include ..\make\rvct\makefiledef