

INCLUDES =  -I .\\  -I..\inc\\  -I..\qlinc\\

OBJS= main.o GSM_GPRS.o TCP_IP.o MRW.o para_read.o Fun.o GPRMC.o GPS.o canparareadwrt.o sms_handle.o fota.o SIM_lock.o\

all:listobj $(OBJS)


include ..\makefiledef
