void tw_updatedCanParaRead(void);
void newunit_id(char *);
void type_gps(char *);
void type_unit(char *);
void SI_TI(char *,char *);
void SIM_Apn(char *);
void remote_pararead(void);
void OS_Limit_read(void);
void OS_Lmt_wrt(char *,char *,char *,char *);
void TCP_para(char *,char *);
void SMTP_para(char *,char *,char *,char *);
void FTP_para(char *,char *,char *,char *);
void CAN_Dump(void);
void PO_STAT_WRITE(void);
void PO_STAT_READ(void);
void Gen_DevDetail_Stmp(void);
void PO_GEN_WRITE(void);
void PF_GEN_WRITE(void);
void code_ver(void);
